FROM golang:1.24.1-bullseye AS base

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

# Install github.com/cespare/reflex
RUN GOBIN=/bin go install github.com/cespare/reflex@v0.3.1
RUN PATH=$PATH:/bin

# Clean cache, as we want all modules in the container to be under /go/.go/path
RUN go clean -modcache

# Map between the working directories of dev and live
RUN ln -s /go /dp-search-api
WORKDIR /dp-search-api
