---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.12

inputs:
  - name: dp-search-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-search-api/ci/scripts/build.sh
